name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Select which test to run (TC-1, TC-12, TC-18, API)'
        required: true
        default: 'all'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_modules_path: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Upload node_modules and Playwright
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: |
            node_modules
            playwright/.local-browsers

  TC-1:
    needs: setup
    if: ${{ github.event.inputs.test_file == 'TC-1' || github.event.inputs.test_file == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: ./ 

      - run: npx playwright test tests/TC-1/signUp.spec.js

  TC-12:
    needs: setup
    if: ${{ github.event.inputs.test_file == 'TC-12' || github.event.inputs.test_file == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: ./ 

      - run: npx playwright test tests/TC-12/addProductsIntoCart.spec.js

  TC-18:
    needs: setup
    if: ${{ github.event.inputs.test_file == 'TC-18' || github.event.inputs.test_file == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: ./ 

      - run: npx playwright test tests/TC-18/viewCategoryProducts.spec.js

  API:
    needs: setup
    if: ${{ github.event.inputs.test_file == 'API' || github.event.inputs.test_file == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: ./ 

      - run: npx playwright test tests/API-1,2,4,9/API-1,2,4,9.spec.js